name: "values-blame"
version: "0.1.0"
usage: "Show which values files contribute to each configuration value"
description: |-
  Identify which values.yaml file edits a specific line when you have multiple
  values.yaml files in your Helm deployment. This is particularly useful for
  debugging and understanding the impact of multiple configuration files.
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/values-blame"
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/values-blame"
  - os: linux
    arch: arm64
    command: "$HELM_PLUGIN_DIR/values-blame"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/values-blame"
  - os: darwin
    arch: arm64
    command: "$HELM_PLUGIN_DIR/values-blame"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/values-blame.exe"
