name: Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o values-blame-linux-amd64
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o values-blame-linux-arm64
        
        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -o values-blame-darwin-amd64
        
        # macOS ARM64
        GOOS=darwin GOARCH=arm64 go build -o values-blame-darwin-arm64
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o values-blame-windows-amd64.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          values-blame-linux-amd64
          values-blame-linux-arm64
          values-blame-darwin-amd64
          values-blame-darwin-arm64
          values-blame-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
